spring:
  datasource:
    url: jdbc:mysql://localhost:3306/barbearia_db?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: '!cEking452'
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect